displayName=TerpinheimerCC
author=FadedOSRS
description=A Clan plug in for the CC Terpinheimer. Home hub, Wise Old Man SOTW & BOTW, website calendar & web events, clan event attendance, live clan map API, party loot log, optional Discord webhooks.
tags=cc,clan,livemap,terpinheimer,wom,sotw,botw,discord,leaderboard,attendance
plugins=com.terpinheimer.TerpinheimerPlugin
